version: "3"
services:
  prometheus_server:
    image: prom/prometheus:v2.30.3
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    privileged: true
    networks:
      static:
        ipv4_address: 172.16.187.20

  grafana_server:
    image: grafana/grafana:9.5.12
    volumes:
      - grafana_configuration:/etc/grafana
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    privileged: true

  vmware_exporter:
    image: pryorda/vmware_exporter:v0.18.4
    ports:
      - 9272:9272
    environment:
      - VSPHERE_HOST=192.168.1.10
      - VSPHERE_USER=administrator@vcenter.local
      - VSPHERE_PASSWORD=Password1234*
      - VSPHERE_IGNORE_SSL=True
    networks:
      static:
        ipv4_address: 172.16.187.30

volumes:
  prometheus_data:
  grafana_configuration:
  grafana_data:

networks:
  static:
    ipam:
      config:
        - subnet: 172.16.187.0/24
